run:
  concurrency: 4
  timeout: 5m
  skip-dirs:
    - vendor
linters:
  enable:
    - bodyclose
    - deadcode
    - errcheck
    - goimports
    - errorlint
    - exportloopref
    - gci
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - typecheck
    - unparam
    - unused
    - varcheck
linters-settings:
  goimports:
    local-prefixes: github.com/argoproj-labs/multi-cluster-kubernetes/
  gosec:
    includes:
      - G304
      - G307
